---

- name: Create Build Info dir
  ansible.builtin.file:
    path: "{{ _cd_build.info.dir }}"
    state: directory
    owner: "{{ _cd_build.info.user }}"
    group: "{{ _cd_build.info.group }}"
    mode: 0755

- name: Install Build Info file
  ansible.builtin.template:
    src: artifact.yml.j2
    dest: "{{ _cd_build.info.dir }}/{{ artifact }}.yml"
    owner: "{{ _cd_build.info.user }}"
    group: "{{ _cd_build.info.group }}"
    mode: 0640
