---

- name: "Check Git-Commit for artifact '{{ artifact }}'"
  include_tasks: "check-git-commit.yml"
  vars:
    # This is the target dir of the artifact
    artifact_dir: "{{ src_dir }}"
    # This is a filename pattern that should be searched for in the artifact_dir.
    # The result of that find will be checked.
    artifact_filename_pattern: "{{ _cd_build.artifacts[artifact].artifact.filename }}"
    # This should fail it won't match because that is the artifact that will be installed.
    fail_if_not_matched: yes

- name: Install 'war' file
  copy:
    src: "{{ src_dir }}/{{ _cd_build.artifacts[artifact].artifact.filename }}"
    dest: "{{ _cd_build.artifacts[artifact].install.dir }}/{{ _cd_build.artifacts[artifact].install.filename }}"
    owner: "{{ _cd_build.artifacts[artifact].install.user }}"
    group: "{{ _cd_build.artifacts[artifact].install.group }}"
    mode: 0644
    remote_src: yes

- name: "Install Build Info for artifact '{{ artifact }}'"
  include_tasks: install-build-info.yml
