---

- name: Create temp file
  tempfile:
    state: file
  register: tempfile

- name: GPG Public Key
  block:

    - name: Install GPG Public Key
      copy:
        src: "jenkins@centerdevice.de.pub"
        dest: "{{ tempfile.path }}"
        owner: root
        group: root
        mode: 0600

    - name: Import GPG Public Key # noqa no-changed-when
      command: gpg --import {{ tempfile.path }}

  always:

    - name: Cleanup temp file
      file:
        name: "{{ tempfile.path }}"
        state: absent
