---
- name: Install GPG Public Key
  ansible.builtin.include_tasks: install-gpg-key.yml
  when: not _cd_build.use_local_artifacts | default(false)

- name: Download and install artifacts if not already installed
  ansible.builtin.include_tasks: install-if-needed.yml
  vars:
    artifact: "{{ item.key }}"
  with_dict: "{{ _cd_build.artifacts }}"
